

import java.awt.*;



import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tolga
 */
public class mainscreen extends javax.swing.JFrame {

    /**
     * Creates new form mainscreen
     */
    
    
    
    public mainscreen() {
        initComponents();
        lblKullAd.setText("Merhaba,"+login.isim);
       
        this.setLocationRelativeTo(null); //formu ortalar
    }
    
    Date tarih = new Date();
    SimpleDateFormat format = new SimpleDateFormat("yyyy MM dd");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ana = new javax.swing.JPanel();
        side = new javax.swing.JPanel();
        bilgi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblKullAd = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        cars = new javax.swing.JPanel();
        lblaraclar = new javax.swing.JLabel();
        customers = new javax.swing.JPanel();
        lblmusteriler = new javax.swing.JLabel();
        rent = new javax.swing.JPanel();
        lblkiralama = new javax.swing.JLabel();
        aracekle = new javax.swing.JPanel();
        lblaraceklesil = new javax.swing.JLabel();
        musteriekle = new javax.swing.JPanel();
        lblmusteriekle = new javax.swing.JLabel();
        cikis = new javax.swing.JPanel();
        lblcikis = new javax.swing.JLabel();
        trh = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        top = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sahne = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setUndecorated(true);

        ana.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side.setBackground(new java.awt.Color(102, 153, 255));
        side.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bilgi.setBackground(new java.awt.Color(102, 153, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/avatar3.png"))); // NOI18N

        lblKullAd.setFont(new java.awt.Font("Kozuka Gothic Pr6N B", 0, 18)); // NOI18N
        lblKullAd.setForeground(new java.awt.Color(255, 255, 255));
        lblKullAd.setText("jLabel5");

        javax.swing.GroupLayout bilgiLayout = new javax.swing.GroupLayout(bilgi);
        bilgi.setLayout(bilgiLayout);
        bilgiLayout.setHorizontalGroup(
            bilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bilgiLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(bilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKullAd)
                    .addComponent(jLabel4))
                .addGap(68, 68, 68))
        );
        bilgiLayout.setVerticalGroup(
            bilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bilgiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lblKullAd)
                .addGap(19, 19, 19))
        );

        side.add(bilgi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 180));

        menu.setBackground(new java.awt.Color(204, 204, 204));
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuMouseExited(evt);
            }
        });
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cars.setBackground(new java.awt.Color(204, 204, 204));
        cars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carsMouseExited(evt);
            }
        });

        lblaraclar.setFont(new java.awt.Font("Kozuka Gothic Pr6N B", 0, 18)); // NOI18N
        lblaraclar.setForeground(new java.awt.Color(255, 255, 255));
        lblaraclar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/car.png"))); // NOI18N
        lblaraclar.setText("   Araçlar");

        javax.swing.GroupLayout carsLayout = new javax.swing.GroupLayout(cars);
        cars.setLayout(carsLayout);
        carsLayout.setHorizontalGroup(
            carsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carsLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblaraclar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        carsLayout.setVerticalGroup(
            carsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblaraclar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.add(cars, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 70));

        customers.setBackground(new java.awt.Color(204, 204, 204));
        customers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customersMouseExited(evt);
            }
        });

        lblmusteriler.setFont(new java.awt.Font("Kozuka Gothic Pr6N B", 0, 18)); // NOI18N
        lblmusteriler.setForeground(new java.awt.Color(255, 255, 255));
        lblmusteriler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/customer.png"))); // NOI18N
        lblmusteriler.setText("Müşteriler");

        javax.swing.GroupLayout customersLayout = new javax.swing.GroupLayout(customers);
        customers.setLayout(customersLayout);
        customersLayout.setHorizontalGroup(
            customersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customersLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblmusteriler, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        customersLayout.setVerticalGroup(
            customersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblmusteriler, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menu.add(customers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 250, 70));

        rent.setBackground(new java.awt.Color(204, 204, 204));
        rent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rentMouseExited(evt);
            }
        });

        lblkiralama.setBackground(new java.awt.Color(255, 255, 255));
        lblkiralama.setFont(new java.awt.Font("Kozuka Gothic Pr6N B", 0, 18)); // NOI18N
        lblkiralama.setForeground(new java.awt.Color(255, 255, 255));
        lblkiralama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rent.png"))); // NOI18N
        lblkiralama.setText("Kiralama");
        lblkiralama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblkiralamaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout rentLayout = new javax.swing.GroupLayout(rent);
        rent.setLayout(rentLayout);
        rentLayout.setHorizontalGroup(
            rentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblkiralama, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        rentLayout.setVerticalGroup(
            rentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblkiralama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.add(rent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 250, 70));

        aracekle.setBackground(new java.awt.Color(204, 204, 204));
        aracekle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aracekleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aracekleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aracekleMouseExited(evt);
            }
        });

        lblaraceklesil.setBackground(new java.awt.Color(255, 255, 255));
        lblaraceklesil.setFont(new java.awt.Font("Kozuka Gothic Pr6N B", 0, 18)); // NOI18N
        lblaraceklesil.setForeground(new java.awt.Color(255, 255, 255));
        lblaraceklesil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        lblaraceklesil.setText("Araç Ekle-Sil");

        javax.swing.GroupLayout aracekleLayout = new javax.swing.GroupLayout(aracekle);
        aracekle.setLayout(aracekleLayout);
        aracekleLayout.setHorizontalGroup(
            aracekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aracekleLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblaraceklesil)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        aracekleLayout.setVerticalGroup(
            aracekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aracekleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblaraceklesil, javax.swing.GroupLayout.PREFERRED_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.add(aracekle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 250, 70));

        musteriekle.setBackground(new java.awt.Color(204, 204, 204));
        musteriekle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                musteriekleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                musteriekleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                musteriekleMouseExited(evt);
            }
        });

        lblmusteriekle.setFont(new java.awt.Font("Kozuka Gothic Pr6N B", 0, 18)); // NOI18N
        lblmusteriekle.setForeground(new java.awt.Color(255, 255, 255));
        lblmusteriekle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/addcars.png"))); // NOI18N
        lblmusteriekle.setText("Müşteri Ekle");

        javax.swing.GroupLayout musteriekleLayout = new javax.swing.GroupLayout(musteriekle);
        musteriekle.setLayout(musteriekleLayout);
        musteriekleLayout.setHorizontalGroup(
            musteriekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, musteriekleLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(lblmusteriekle, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        musteriekleLayout.setVerticalGroup(
            musteriekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musteriekleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblmusteriekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.add(musteriekle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 250, 70));

        cikis.setBackground(new java.awt.Color(204, 204, 204));
        cikis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cikisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cikisMouseExited(evt);
            }
        });

        lblcikis.setFont(new java.awt.Font("Kozuka Gothic Pr6N B", 0, 18)); // NOI18N
        lblcikis.setForeground(new java.awt.Color(255, 255, 255));
        lblcikis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cikis.png"))); // NOI18N
        lblcikis.setText("Çıkış");
        lblcikis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcikisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblcikisMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout cikisLayout = new javax.swing.GroupLayout(cikis);
        cikis.setLayout(cikisLayout);
        cikisLayout.setHorizontalGroup(
            cikisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cikisLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblcikis, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        cikisLayout.setVerticalGroup(
            cikisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cikisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcikis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.add(cikis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 250, 70));

        side.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, 420));

        trh.setFont(new java.awt.Font("Kozuka Gothic Pr6N B", 0, 18)); // NOI18N
        trh.setForeground(new java.awt.Color(255, 255, 255));
        trh.setText(format.format(tarih));
        side.add(trh, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, -1, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/copy.png"))); // NOI18N
        side.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 630, -1, -1));

        ana.add(side, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 700));

        top.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/carpi.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Kozuka Gothic Pr6N B", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Düzce Oto Kiralama");

        javax.swing.GroupLayout topLayout = new javax.swing.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(31, 31, 31))
        );

        ana.add(top, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 750, 120));

        sahne.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout sahneLayout = new javax.swing.GroupLayout(sahne);
        sahne.setLayout(sahneLayout);
        sahneLayout.setHorizontalGroup(
            sahneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        sahneLayout.setVerticalGroup(
            sahneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        ana.add(sahne, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 750, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
     
    
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuMouseExited

    private void carsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carsMouseExited
        // TODO add your handling code here:
       cars.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_carsMouseExited

    private void carsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carsMouseEntered
        // TODO add your handling code here:
        cars.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_carsMouseEntered

    private void customersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customersMouseExited
        // TODO add your handling code here:
        customers.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_customersMouseExited

    private void customersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customersMouseEntered
        // TODO add your handling code here:
        customers.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_customersMouseEntered

    private void aracekleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aracekleMouseExited
        // TODO add your handling code here:
        aracekle.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_aracekleMouseExited

    private void aracekleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aracekleMouseEntered
        // TODO add your handling code here:
        aracekle.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_aracekleMouseEntered

    private void musteriekleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musteriekleMouseExited
        // TODO add your handling code here:
        musteriekle.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_musteriekleMouseExited

    private void musteriekleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musteriekleMouseEntered
        // TODO add your handling code here:
        musteriekle.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_musteriekleMouseEntered

    private void carsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carsMouseClicked
        // TODO add your handling code here:
        sahne.removeAll();
        sahne.repaint();
//        JLabel label = new JLabel("Deneme 134");
//        sahne.add(label);
//        label.setBounds(10, 20, 50, 50);
//        label.setForeground(Color.WHITE);
           araclar nm = null;
        try {
            nm = new araclar("araclar");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(mainscreen.class.getName()).log(Level.SEVERE, null, ex);
        }
           sahne.add(nm.pnl);
           nm.pnl.setBounds(0, 0, 750, 580);
        
        
        
        
    }//GEN-LAST:event_carsMouseClicked

    private void customersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customersMouseClicked
        // TODO add your handling code here:
       sahne.removeAll();
       sahne.repaint();
//        JLabel label = new JLabel("Denemeasdasdasd 134");
//        sahne.add(label);
//        label.setBounds(10, 20, 100, 50);
//        label.setForeground(Color.WHITE);
            musteriler nm = null;
        try {
            nm = new musteriler("musteriler");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(mainscreen.class.getName()).log(Level.SEVERE, null, ex);
        }
           sahne.add(nm.pnr);
           nm.pnr.setBounds(0, 0, 750, 580);

    }//GEN-LAST:event_customersMouseClicked

    private void rentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentMouseExited
        // TODO add your handling code here:
        rent.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_rentMouseExited

    private void rentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentMouseEntered
        // TODO add your handling code here:
        rent.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_rentMouseEntered

    private void rentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentMouseClicked
        // TODO add your handling code here:
        sahne.removeAll();
       sahne.repaint();
        
            kiralama kr = new kiralama("Kiralama");
            sahne.add(kr.pns);
            kr.pns.setBounds(0, 0, 750, 580);
        
    }//GEN-LAST:event_rentMouseClicked

    private void aracekleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aracekleMouseClicked
        // TODO add your handling code here:
        sahne.removeAll();
       sahne.repaint();
        
        araceklesil arack = new araceklesil();
        sahne.add(arack.pnx);
            arack.pnx.setBounds(0, 0, 750, 580);
    }//GEN-LAST:event_aracekleMouseClicked

    private void musteriekleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musteriekleMouseClicked
        // TODO add your handling code here:
        sahne.removeAll();
       sahne.repaint();
       
       musteriekle mekle = new musteriekle();
       sahne.add(mekle.pnz);
       mekle.pnz.setBounds(0, 0, 750, 580);
        
    }//GEN-LAST:event_musteriekleMouseClicked

    private void cikisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cikisMouseExited
        // TODO add your handling code here:
        cikis.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_cikisMouseExited

    private void cikisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cikisMouseEntered
        // TODO add your handling code here:
        cikis.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_cikisMouseEntered

    private void lblcikisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcikisMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblcikisMouseClicked

    private void lblcikisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcikisMouseEntered
        // TODO add your handling code here:
           cikis.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_lblcikisMouseEntered

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
     //   this.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_jLabel1MouseEntered

     private void lblkiralamaMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
          // cikis.setBackground(new Color(102,102,102));
    }           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainscreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ana;
    private javax.swing.JPanel aracekle;
    private javax.swing.JPanel bilgi;
    private javax.swing.JPanel cars;
    private javax.swing.JPanel cikis;
    private javax.swing.JPanel customers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblKullAd;
    private javax.swing.JLabel lblaraceklesil;
    private javax.swing.JLabel lblaraclar;
    private javax.swing.JLabel lblcikis;
    private javax.swing.JLabel lblkiralama;
    private javax.swing.JLabel lblmusteriekle;
    private javax.swing.JLabel lblmusteriler;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel musteriekle;
    private javax.swing.JPanel rent;
    private javax.swing.JPanel sahne;
    private javax.swing.JPanel side;
    private javax.swing.JPanel top;
    private javax.swing.JLabel trh;
    // End of variables declaration//GEN-END:variables
}
